""" CRUD package """
# Import all modules
from . import user
from . import account
from . import book
from . import wishlist
from . import review
from . import follower
from . import search
from . import forum