"""add_followers

Revision ID: 6b8055e88ddb
Revises: 5271553086e3
Create Date: 2024-11-23 10:51:19.746067

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = '6b8055e88ddb'
down_revision = '5271553086e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('follower_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('following_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.ForeignKeyConstraint(['follower_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follower')
    # ### end Alembic commands ###
