"""add_followers

Revision ID: a2c949237169
Revises: 5271553086e3
Create Date: 2024-11-24 18:05:40.103052

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'a2c949237169'
down_revision = '5271553086e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('follower',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('follower_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.Column('following_id', sqlmodel.sql.sqltypes.GUID(), nullable=False),
    sa.ForeignKeyConstraint(['follower_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['following_id'], ['account.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('follower')
    # ### end Alembic commands ###
