"""add_forum

Revision ID: f1d4048307ed
Revises: 795bca2f2245
Create Date: 2024-12-08 10:38:52.076367

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision = 'f1d4048307ed'
down_revision = '795bca2f2245'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('forum',
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('img', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('account_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('parent_forum_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('dislikes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['parent_forum_id'], ['forum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('forumreaction',
    sa.Column('id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('forum_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('account_id', sqlmodel.sql.sqltypes.GUID(), nullable=True),
    sa.Column('type', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['account.id'], ),
    sa.ForeignKeyConstraint(['forum_id'], ['forum.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('forumreaction')
    op.drop_table('forum')
    # ### end Alembic commands ###
